import { Button, Icon, Tabbar, TabbarItem, NavBar, Toast, Search, Swipe, SwipeItem, Grid, GridItem, Rate, ActionSheet, Checkbox, Dialog, RadioGroup, Radio, Form, Field, Cascader, Popup } from 'vant'
import Vue from 'vue'
Vue.use(Button)
Vue.use(Icon)
Vue.use(Tabbar)
Vue.use(TabbarItem)
Vue.use(NavBar)
Vue.use(Toast)
Vue.use(Search)
Vue.use(Swipe)
Vue.use(SwipeItem)
Vue.use(Grid)
Vue.use(GridItem)
Vue.use(Rate)
Vue.use(ActionSheet)
Vue.use(Checkbox)
Vue.use(Dialog)
Vue.use(RadioGroup)
Vue.use(Radio)
Vue.use(Form)
Vue.use(Field)
Vue.use(Cascader)
Vue.use(Popup)
